# Corvus onboard computer (Raspberry Pi 4)
# Pixhawk 6C mini using PX4 -usb-> onboard computer (UDP 14550 and TCP 5760)

[General]
TcpServerPort=5760
ReportStats=false
MavlinkDialect=auto

[UartEndpoint fc]
Device=/dev/autopilot
Baud=115200

[UdpEndpoint qgc]
Mode=Server
Address=0.0.0.0
Port=14550
